Repository viadonau/Pegelhub-Frontend, pull requests merged in 2024-06, with the labels that each got.

#11 PGL-22 Create component-test.yml
  .github/workflows/component-test.yml
  angular.json
  cypress.config.ts
  package-lock.json
  package.json
Labels: enhancement

#13 Adjustments - Component Tests Pipeline
  .github/workflows/component-tests.yml
Labels: enhancement

#14 PGL-22: added e2e tests
  .github/workflows/component-tests.yml
  .github/workflows/e2e-test.yml
  cypress.config.ts
  package.json
Labels: enhancement

#15 build: adjusted docker and nginx settings
  Dockerfile
  README.md
  angular.json
  docker-compose.yml
  nginx.conf
Labels: documentation, enhancement

#16 ci: adjusted e2e and comp test pipelines
  .github/workflows/component-tests.yml
  .github/workflows/e2e-test.yml
  package.json
Labels: bug

#17 build: added environment adjustments
  Dockerfile
  angular.json
  nginx.conf
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/proxy.conf.json
Labels: enhancement
